apiVersion: v1
name: harbor
version: 1.15.1-artemeon
appVersion: 2.11.1
description: An open source trusted cloud native registry that stores, signs, and scans content
keywords:
  - docker
  - registry
  - harbor
home: https://goharbor.io
icon: https://raw.githubusercontent.com/goharbor/website/main/static/img/logos/harbor-icon-color.png
sources:
  - https://github.com/goharbor/harbor
  - https://github.com/artemeon/harbor-helm
maintainers:
  - name: Andreas Behrend
    email: andreas.behrend@artemeon.de
engine: gotpl
